# Generated by Django 2.1.1 on 2018-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
