# Generated by Django 2.1.1 on 2018-11-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('goodsUrl', models.CharField(max_length=60)),
                ('goodsId', models.CharField(max_length=20)),
                ('goodsPrice', models.CharField(max_length=30)),
                ('goodsCommentCount', models.CharField(max_length=10)),
                ('hp', models.CharField(max_length=10)),
                ('zp', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
            ],
        ),
    ]
